name: Deploy React App to EC2

on:
  push:
    branches:
      - master # Triggers when you push to the 'master' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Execute SSH commands on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd /home/ubuntu/my-react-app
            git pull origin master
            npm install
            npm run build
            sudo cp -r dist/* /var/www/html/
            sudo systemctl restart nginx